CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT UNIQUE NOT NULL, hashed_password TEXT NOT NULL, name TEXT, role TEXT NOT NULL DEFAULT 'user', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE resumes(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, original_filename TEXT NOT NULL, source_type TEXT NOT NULL, storage_key TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'uploaded', created_at TIMESTAMPTZ DEFAULT now(), deleted_at TIMESTAMPTZ);
CREATE TABLE resume_sections(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resume_id UUID NOT NULL REFERENCES resumes(id) ON DELETE CASCADE, section_type TEXT NOT NULL, raw_text TEXT NOT NULL, normalized_text TEXT, order_index INT NOT NULL);
CREATE TABLE evidence_items(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, resume_id UUID REFERENCES resumes(id) ON DELETE CASCADE, claim_text TEXT NOT NULL, source_span TEXT, verified BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE jobs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, source TEXT NOT NULL, external_id TEXT, company TEXT NOT NULL, title TEXT NOT NULL, location TEXT, employment_type TEXT, experience_level TEXT, description TEXT NOT NULL, application_url TEXT, posted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE job_requirements(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, requirement_type TEXT NOT NULL, requirement_text TEXT NOT NULL, normalized_skill TEXT, priority INT DEFAULT 0);
CREATE TABLE match_reports(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, resume_id UUID NOT NULL REFERENCES resumes(id) ON DELETE CASCADE, job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, score_json JSONB NOT NULL, gaps_json JSONB NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE resume_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, base_resume_id UUID NOT NULL REFERENCES resumes(id) ON DELETE CASCADE, job_id UUID REFERENCES jobs(id) ON DELETE SET NULL, template TEXT NOT NULL, content_json JSONB NOT NULL, docx_storage_key TEXT, pdf_storage_key TEXT, readiness_score NUMERIC(5,2), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE applications(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, resume_version_id UUID REFERENCES resume_versions(id) ON DELETE SET NULL, status TEXT NOT NULL DEFAULT 'saved', applied_at TIMESTAMPTZ, follow_up_at TIMESTAMPTZ);
CREATE TABLE contacts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_id UUID REFERENCES jobs(id) ON DELETE SET NULL, name TEXT NOT NULL, role TEXT, organization TEXT, public_profile_url TEXT, source_url TEXT, confidence NUMERIC(5,2), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE outreach_drafts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL, channel TEXT NOT NULL, subject TEXT, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE audit_logs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, resource_type TEXT, resource_id UUID, metadata_json JSONB, created_at TIMESTAMPTZ DEFAULT now());
