"""
CareerForge AI — Models Package.

SQLAlchemy ORM models mapping to the PostgreSQL schema.
All models use UUID primary keys generated by pgcrypto.

Table relationships:
    User → Resumes → Sections/Evidence
    Job → Requirements
    Resume × Job → MatchReport
    ResumeVersion → Resume/Job
    Contact → Job
    OutreachDraft → Job/Contact
    AuditLog → User (optional)
"""

from app.models.user import User
from app.models.resume import Resume, ResumeSection, EvidenceItem
from app.models.job import Job, JobRequirement
from app.models.match import MatchReport
from app.models.resume_version import ResumeVersion
from app.models.contact import Contact
from app.models.outreach import OutreachDraft
from app.models.audit import AuditLog

__all__ = [
    "User",
    "Resume",
    "ResumeSection",
    "EvidenceItem",
    "Job",
    "JobRequirement",
    "MatchReport",
    "ResumeVersion",
    "Contact",
    "OutreachDraft",
    "AuditLog",
]
